# Generated by Django 4.2.2 on 2023-06-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=20)),
                ('dni', models.IntegerField()),
                ('fecha_alta', models.DateField()),
            ],
        ),
    ]
